Numpy : 다차원 배열을 지원하는 수학 라이브러리

- 동일한 자료형을 갖는 배열
- 접근은 indexing을 이용해서 접근
- 다양한 형태의 수학 함수를 제공

numpy 로딩

In [3]:
import numpy as np

1차원 numpy 배열

In [2]:
list1 = [1, 2, 3, 4, 5]
list1

[1, 2, 3, 4, 5]

In [3]:
# numpy 배열로 변환
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [4]:
print(list1)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [5]:
# 5부터 10까지 숫자로 된 넘파이 배열을 생성, 튜플로도 가능(굳이 그럴 이유는 없음)
arr2 = np.array([5, 6, 7, 8, 9, 10])
arr2

array([ 5,  6,  7,  8,  9, 10])

2차원 배열 생성

In [6]:
# 크기가 맞지 않는 행과 열로 이루어진 배열의 사용은 지양 ex) [[1, 2, 3], [4, 5]]
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

배열의 크기 : 배열명.shape

In [7]:
# 출력은 행, 열의 형태
# 일반적으로 행의 수는 데이터의 수
# 열의 수는 특성(속성)의 수
# 1차원 배열은 행만 존재하는 데이터로 저장 됨
arr3.shape, arr2.shape

((2, 3), (6,))

배열의 값의 갯수 : 배열명.size

In [8]:
print(arr3.size)
print(arr2.size)

6
6


배열에 저장된 데이터 타입 : 배열명.dtype

In [9]:
print(arr3.dtype)

int32


In [10]:
arr4 = np.array([2.3, 1.3, 3.4, 4.5])
print(arr4.dtype)

float64


배열의 차원 수 : 배열명.ndim

In [11]:
print(arr2.ndim)
print(arr3.ndim)

1
2


배열을 초기화하는 함수

- np.zeros((행, 열)) : (행, 열) 배열을 0으로 초기화

In [12]:
arr4 = np.zeros((2, 2))

arr4

array([[0., 0.],
       [0., 0.]])

In [13]:
arr5 = np.zeros((3, 7))

arr5

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

- np.ones((행, 열)) : (행, 열) 배열을 1로 초기화

In [14]:
arr5 = np.ones((3, 4))

arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- np.full((행, 열), 값) : (행, 열) 배열을 값으로 초기화

In [15]:
arr6 = np.full((3,4), 7)

arr6

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [16]:
# 5회차별 로또 번호를 저장하는 배열을 3값으로 초기화
# 5행 7열 행렬
arr7 = np.full((5, 7), 3)
arr7

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

np.arange(시작값, 끝값+1, 증가값) : 시작값부터 끝값까지 증가값만큼 증가시켜가면서 숫자배열을 생성

In [17]:
arr8 = np.arange(1, 11, 1)

arr8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# 주사위 숫자를 배열로 생성
arr9 = np.arange(1, 7, 1)
arr9

array([1, 2, 3, 4, 5, 6])

데이터 타입을 설정해서 배열을 생성 : dtype 파라미터

In [19]:
# np.float64 : 실수형 8바이트 타입
arr10 = np.array([1, 2, 3, 4], dtype = np.float64)
arr10

array([1., 2., 3., 4.])

In [20]:
arr10.dtype

dtype('float64')

생성된 데이터의 파라미터를 변경하고 싶다면 -> astype() <br>
배열명.astype("타입종류")

In [21]:
arr10 = arr10.astype("int32")
arr10.dtype

dtype('int32')

In [22]:
arr10

array([1, 2, 3, 4])

임의의 값으로 배열 생성

In [23]:
print(np.random.randint(1, 7))

5


In [24]:
# np.random.rand(행, 열)
# 0에서 1 사이 범위의 임의의 숫자로 구성된 배열을 생성
np.random.rand(2, 3)

array([[0.87163166, 0.58899762, 0.03868799],
       [0.95375577, 0.15804296, 0.08788537]])

In [25]:
# 임의의 정수로 구성된 배열을 생성
np.random.randint(1, 6+1, size = (2, 3))

array([[6, 3, 5],
       [6, 2, 3]])

In [26]:
# 1부터 45까지의 숫자 중에서 6개의 숫자를 뽑아서 배열로 생성
# 단 뽑은 숫자는 중복이 되면 안됨
lottoNum = []

while len(lottoNum) < 6:
    num = np.random.randint(1, 46)
    if num in lottoNum:
        pass
    else:
        lottoNum.append(num)
        
lottoNum.sort()

print(lottoNum)

[11, 13, 17, 18, 28, 39]


In [27]:
lottoNum = []

for i in range(6):
    while num in lottoNum:
        num = np.random.randint(1, 46)
    lottoNum.append(num)

lottoNum.sort()
    
print(lottoNum)

[4, 12, 18, 24, 36, 39]


배열의 크기 변경 : reshape(행, 열)
배열명.reshape(행, 열)

In [28]:
arr12 = np.ones((3,4))
arr12.shape

(3, 4)

In [29]:
# 배열의 크기를 변경하는 경우에는 동일한 데이터 수로 변경해야 함
arr12 = arr12.reshape(2, 6)
arr12

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [30]:
arr12 = arr12.reshape(4, 3)
arr12

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
arr13 = np.random.randint(1, 101, size = (3,5))
arr13

array([[53, 96, 94, 61, 93],
       [40, 92, 49,  4, 65],
       [85, 25, 28, 35, 78]])

In [32]:
arr13.reshape(2,8)

ValueError: cannot reshape array of size 15 into shape (2,8)

In [ ]:
# 행의 -1은 행의 크기를 열의 크기에 따라 결정하는 것
arr12 = arr12.reshape(-1, 3)
arr12

In [ ]:
# 열의 -1은 열의 크기를 행의 크기에 따라 결정하는 것
arr12 = arr12.reshape(2, -1)
arr12

flatten() : 배열을 1차원으로 변환

In [ ]:
arr12.shape

In [ ]:
arr12 = arr12.flatten()
arr12.shape

In [ ]:
arr12

In [ ]:
arr13 = [2, 4, 6]
arr14 = [4, 2, 3]

arr13 + arr14

In [ ]:
arr13 = np.array([2, 4, 6])
arr14 = np.array([4, 2, 3])

arr13 + arr14

### 숙제

2개의 넘파이 배열을 사직 연산하는 함수를 작성

- 사칙연산자도 파라미터로 할당

calMetrix(arr1, arr2, "+")

In [ ]:
def calMetrix(arr1, arr2, cal):
    if cal == "+":
        return arr1 + arr2
    elif cal == "-":
        return arr1 - arr2
    elif cal == "*":
        return arr1 * arr2
    elif cal == "/":
        return arr1 / arr2
    elif cal == "//":
        return arr1 // arr2
    elif cal == "%":
        return arr1 % arr2
    
arr15 = calMetrix(arr13, arr14, "/")
arr15

- 인덱싱과 슬라이싱

In [33]:
arr20 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 2, 8, 2],
                 [7, 2, 3, 5]])
arr20

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 2, 8, 2],
       [7, 2, 3, 5]])

In [34]:
arr20[2]

array([9, 2, 8, 2])

In [35]:
arr20[2][3]

2

In [36]:
arr21 = arr20.flatten()
arr21.shape

(16,)

In [38]:
print(arr21[:5])
print(arr21[0:5])

[1 2 3 4 5]
[1 2 3 4 5]


In [40]:
print(arr21[-4:])
print(arr21[12:])

[7 2 3 5]
[7 2 3 5]


In [43]:
list1 = [1, 2, 3, 4, 5]
list1[0:2] = [10]
list1

[10, 3, 4, 5]

In [44]:
list1 = [1, 2, 3, 4, 5]
list1[0:2] = [10, 10]
list1

[10, 10, 3, 4, 5]

In [45]:
arr22 = np.array(list1)

arr22[0:2] = 10
arr22

array([10, 10,  3,  4,  5])

In [49]:
# 뒤에 2개 값을 20으로 변경
list1 = [1, 2, 3, 4, 5]
arr22 = np.array(list1)
arr22[-2:] = 20
arr22

array([ 1,  2,  3, 20, 20])

In [58]:
arr20 = np.array([[3, 4, 6, 8],
                 [6, 7, 4, 9],
                 [1, 4, 3, 9],
                 [9, 2, 4, 1]])

2차원 배열의 슬라이싱

배열명[행의시작인덱스:행의끝인덱스+1, 열의시작인덱스:열의끝인덱스+1]

In [59]:
arr20[:2, :2]

array([[3, 4],
       [6, 7]])

In [60]:
arr20[1:, 1:3]

array([[7, 4],
       [4, 3],
       [2, 4]])

In [61]:
arr20[1:, 1:2]

array([[7],
       [4],
       [2]])

똑같은 값을 뽑지만 인덱스를 사용하는 것과 슬라이싱을 사용하는 것은 결과가 다름

In [62]:
arr20[1:, 1]

array([7, 4, 2])

In [63]:
arr20[3, 1:]

array([2, 4, 1])

In [65]:
print(arr20[0][3])
print(arr20[0, 3])

8
8


In [68]:
print(arr20[3][3])
print(arr20[3, 3])

1
1


### boolean 인덱싱

- 조건에 맞는 값만 표시하거나 가져오는 것

In [70]:
arr23 = np.array([12, 40, 22, 33, 23])

In [71]:
arr23 > 20

array([False,  True,  True,  True,  True])

In [72]:
arr23[arr23 > 20]

array([40, 22, 33, 23])

arr23에서 짝수만 출력

In [73]:
arr23[arr23 % 2 == 0]

array([12, 40, 22])

arr23에서 짝수인 값을 0으로 변경

In [75]:
arr23[arr23 % 2 == 0] = 0
arr23

array([ 0,  0,  0, 33, 23])

arr23에서 20보다 큰 값은 100으로 변경

In [77]:
arr23 = np.array([12, 40, 22, 33, 23])
arr23[arr23 >= 20] = 100
arr23

array([ 12, 100, 100, 100, 100])

arr23에서 20보다 큰 값은 100으로 변경

In [80]:
arr23 = np.array([12, 40, 22, 33, 23])
arr23[np.logical_and(arr23 >=20, arr23 < 40)] = 100
arr23

array([ 12,  40, 100, 100, 100])

In [82]:
# 배열의 합
print(arr23.sum())
print(np.sum(arr23))

352
352


In [83]:
# 배열의 평균
print(arr23.mean())
print(np.mean(arr23))

70.4
70.4


In [85]:
# 배열의 제곱근
print(np.sqrt(arr23))

[ 3.46410162  6.32455532 10.         10.         10.        ]


### 외부 데이터 파일을 불러와서 데이터 분석하기

In [4]:
# delimiter = "," : ,를 제거하고 데이터를 부름
data = np.loadtxt("height_weight.txt", delimiter = ",")
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [88]:
print(data.shape)

(2, 10)


bmi 지수 계산

bmi = (몸무게 / 키 * 키) * 100

In [5]:
# 키와 몸무게를 분리
hei = data[0]
wei = data[1]

bmi = (wei / (hei * hei)) * 100

np.round(bmi, 2) # 소수점 둘째자리에서 반올림

array([0.21, 0.27, 0.26, 0.24, 0.16, 0.2 , 0.23, 0.22, 0.24, 0.26])